### Метод Якоби

In [ ]:
import numpy as np

def jacobi(A, b, x0=None, eps=1e-8, max_iter=1000):
    A = np.asarray(A, dtype=float)
    b = np.asarray(b, dtype=float)
    n = len(b)
    x = np.zeros(n) if x0 is None else np.array(x0, dtype=float)
    for _ in range(max_iter):
        x_new = np.zeros(n)
        for i in range(n):
            s = (A[i, :i] @ x[:i]).sum() + (A[i, i+1:] @ x[i+1:]).sum()
            x_new[i] = (b[i] - s) / A[i, i]
        if np.linalg.norm(x_new - x, np.inf) < eps:
            return x_new
        x = x_new
    return x

In [ ]:
A = np.array([[4, -1,  0],
              [-1, 4, -1],
              [0, -1,  4]], dtype=float)
b = np.array([2, 4, 10], dtype=float)

x = jacobi(A, b)
A @ x

array([1.99999999, 4.        , 9.99999999])

### Метод Зейделя

In [ ]:
def seidel(A, b, x0=None, eps=1e-8, max_iter=1000):
    A = np.asarray(A, dtype=float)
    b = np.asarray(b, dtype=float)
    n = len(b)
    x = np.zeros(n) if x0 is None else np.array(x0, dtype=float)
    for _ in range(max_iter):
        x_old = x.copy()
        for i in range(n):
            s = (A[i, :i] @ x[:i]).sum() + (A[i, i+1:] @ x[i+1:]).sum()
            x[i] = (b[i] - s) / A[i, i]
        if np.linalg.norm(x - x_old, np.inf) < eps:
            return x
    return x

In [ ]:
x = seidel(A, b)
A @ x

array([ 2.,  4., 10.])

In [ ]:
def sor(A, b, omega=1.5, x0=None, eps=1e-8, max_iter=1000):
    A = np.asarray(A, dtype=float)
    b = np.asarray(b, dtype=float)
    n = len(b)
    x = np.zeros(n) if x0 is None else np.array(x0, dtype=float)
    for _ in range(max_iter):
        x_old = x.copy()
        for i in range(n):
            s = (A[i, :i] @ x[:i]).sum() + (A[i, i+1:] @ x[i+1:]).sum()
            x_gs = (b[i] - s) / A[i, i]
            x[i] = (1 - omega) * x[i] + omega * x_gs
        if np.linalg.norm(x - x_old, np.inf) < eps:
            return x
    return x

In [ ]:
x = sor(A, b)
A @ x

array([ 2.00000001,  4.        , 10.        ])

In [ ]:
n = 100
A = np.random.uniform(0.1, 0.9, (n, n))
A += np.identity(n) * np.random.uniform(1, 10, n)
U, S, V = np.linalg.svd(A)


b = np.ones(n)
S.max() / S.min()

np.float64(129.82930828189467)

In [ ]:
%%time
x = jacobi(A, b)
np.linalg.norm(A @ x - b) < 1e-5

/tmp/ipykernel_5084/3355325354.py:11: RuntimeWarning: overflow encountered in matmul
  s = (A[i, :i] @ x[:i]).sum() + (A[i, i+1:] @ x[i+1:]).sum()


CPU times: user 1.12 s, sys: 1.7 ms, total: 1.12 s
Wall time: 1.13 s


np.False_

In [ ]:
%%time
x = seidel(A, b)
np.linalg.norm(A @ x - b) < 1e-5

CPU times: user 313 ms, sys: 2.99 ms, total: 316 ms
Wall time: 317 ms


np.True_

In [ ]:
%%time
x = sor(A, b, omega=0.6)
np.linalg.norm(A @ x - b) < 1e-5

CPU times: total: 188 ms
Wall time: 215 ms


np.True_